version: "3.3"

services:
  nginx:
    image: mattlangsenkamp/todotree-static-server
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - type: bind
        source: /etc/letsencrypt/live/
        target: /etc/letsencrypt/live/
